spring:
  application:
    name: zenfood-api
  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/zendb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver