spring:
  application:
    name: zenfood-api
  jpa:
    database: H2
    show-sql: true
    properties:
#      javax:
#        persistence:
#          schema-generation.scripts.action: create
#          schema-generation.scripts.create-target: src/main/resources/schema.sql
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:C:\\DataBases\\zendb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 3
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baseline-on-migrate: true
  jackson:
    deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false